// Generated by https://quicktype.io

export interface BusStopOfRoute {
  RouteUID: string;
  RouteID: string;
  RouteName: NameType;
  Operators: RouteOperator[];
  SubRouteUID: string;
  SubRouteID: string;
  SubRouteName: NameType;
  Direction: number;
  City: string;
  CityCode: string;
  Stops: Stop[];
  UpdateTime: Date;
  VersionID: number;
}


export interface RouteOperator {
  OperatorID: string;
  OperatorName: NameType;
  OperatorCode: string;
  OperatorNo: string;
}

export interface NameType {
  Zh_tw: string;
  En: string;
}

export interface Stop {
  StopUID: string;
  StopID: string;
  StopName: NameType;
  StopBoarding: number;
  StopSequence: number;
  StopPosition: PointType;
  StationID: string;
  StationGroupID: string;
  LocationCityCode: string;
}

export interface PointType {
  PositionLon: number;
  PositionLat: number;
  GeoHash: string;
}
